spring:
  cloud:
    gateway:
      routes:
        - id: serviceA
          uri: http://localhost:8080
          predicates:
            - Path=/user/**


        - id: serviceB
          uri: http://localhost:8081
          predicates:
            - Path=/customer/**


server:
 port: 3030
